spring:
  application:
    name: redis-study
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 60000

  cache:
    type: redis
    redis:
      cache-null-values: false
